name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Stage 1: Testing the application
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Backend Tests
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore dependencies
        run: dotnet restore Master/Master.sln
      - name: Run Backend Tests
        run: dotnet test Master/Master.sln --no-restore --verbosity normal

  # Stage 2: Build and Push Docker images
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Build and Push Backend
      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./Master
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/master-backend:latest

      # Build and Push Frontend
      - name: Build and push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./Masterrio
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/master-frontend:latest
